[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".local/bin/k0sctl"]
    type = "file"
    url = "https://github.com/k0sproject/k0sctl/releases/download/v0.15.0/k0sctl-linux-x64"
    executable = true
    refreshPeriod = "168h"
