#!/bin/bash
git-review() {
    local target_branch
    target_branch="${1:-master}"
    git log --patch --reverse "${target_branch}..HEAD"
}

gmru() {
    # List all recently used branches within a git repo.
    # Mnemonic: "git most recently used"
    git for-each-ref --count="${1:-10}" \
        --sort=-committerdate refs/heads/ \
        --format='%(committerdate:relative) %09 %(objectname:short) %09 %(refname:short) %09 %(authorname)'
}

# List names of all contributors to a git repo
git-contributors() {
    git ls-tree -r -z --name-only HEAD -- "$1" \
        | xargs -0 -n1 git blame --line-porcelain HEAD \
        | grep  "^author " \
        | sort | uniq -c | sort -nr
}

# Open all files by extension
editall() {
    local file_ext
    file_ext="$1"
    shift 1
    fd -e "$file_ext" . -X vim -p
}

mkvenv() {
    mkvirtualenv -a "$PWD" "$(basename "$PWD")" -p "$(which python3)"
}

# Verify that emojis can display in terminal.
# Taken from starship docs:
# https://starship.rs/faq/#why-don-t-i-see-a-glyph-symbol-in-my-prompt
emoji-test() {
    printf "Snake icon: "
    echo -e "\xf0\x9f\x90\x8d"
    printf "Powerline branch: "
    echo -e "\xee\x82\xa0"
}

# Switch to a project directory.
# Replaces `virtualenvwrappers`'s alias,
# leveraging the muscle memory but relying on direnv.
workon() {
    local project_name
    project_name="${1:-}"
    shift 1
    d="${HOME}/src/$project_name"
    pushd "$d" || return 1
}

# Remove an warm light / darkness customization
bright() {
    killall redshift || true > /dev/null 2>&1
    redshift -x
}

# Set evening time laptop lighting.
warm() {
    bright
    redshift -o -O 3700 -b "1"
}

# Set night time laptop lighting.
dark() {
    bright
    redshift -o -O 3700 -b "0.8"
}
