model_provider = "ollama-ruindev"
profile = "ollama-ruindev"

[model_providers.ollama-ruindev]
name = "OllamaRuinDev"
# base_url = "http://localhost:11434/v1"
base_url = "http://tartessos.ruindev.wg:6666/v1"
# base_url = "https://llm.ruin.dev/v1"
env_key = "OLLAMA_API_KEY"
wire_api = "responses"

[profiles.ollama-ruindev]
model = "qwen3.6:35b-a3b"
# model = "gemma4:31b"
# model = "gemma4:26b"
model_provider = "ollama-ruindev"
