# Run shellcheck
lint:
  fd -t f -X file --mime \
    | perl -F: -lanE '$F[1] =~ /text\/x-shellscript/ and say $F[0]' \
    | xargs -r shellcheck
  gum format -t emoji "All scripts passed lint :rocket:"

# Copy local rip dir to remote
push:
  rsync -a --info=progress2 "$HOME/music/ripping" "/mnt/Valhalla/Media/incoming/new-music/"

# Rip an album
rip:
  ./rip-album
