#!/bin/bash
# Script to split a combined FLAC file into multiple track FLAC files,
# based on a CUE file describing the splits. For reference, see
# https://unix.stackexchange.com/questions/10251/how-do-i-split-a-flac-with-a-cue
set -euo pipefail


# Check for deps
if ! hash shnsplit > /dev/null 2>&1 ; then
  gum log --log error "'shnsplit' command not found; install 'cuetools' and/or 'shntool'"
  exit 1
fi

# We're just gonna use PWD here.
cue_file="$(fd -t f -e cue . "$PWD")"

# Sanity check that there's a single CUE file.
if [[ "$(wc -l <<< "$cue_file")" -gt 1 ]] ; then
  gum log --log error "Found multiple CUE files, got confused, exiting"
  exit 1
fi

fd -t f -e flac . "$PWD" -X \
  shnsplit -f "$cue_file" -t %n-%t -o flac
