#!/bin/bash
# Script to apply ID3 tags manually to a set of local FLAC files.
# Used as a fallback if album is not found on MusicBrainz.
set -euo pipefail


# TODO: require dir to be specified; right now just uses CWD.
album_dir="${1:-}"
if [[ -z "$album_dir" ]] ; then
  gum log --level warn --time datetime "No directory provided, or supported, using CWD..."
  album_dir="$PWD"
fi

if [[ "$(fd -t f -e flac . "$album_dir" | wc -l)" -eq 0 ]] ; then
  gum log --level error --time datetime "No FLAC files found in $album_dir, exiting"
  exit 1
fi

# Prompt for vars.
artist="$(gum input --prompt "Artist name: " --placeholder "Enter name of artist")"
album_name="$(gum input --prompt "Album name: " --placeholder "Enter name of album")"
release_year="$(gum input --prompt "Release year: " --placeholder "Enter year album was released")"

# Switch dirs so that relpaths don't contain dots or slash prefixes
pushd "$album_dir" > /dev/null 2>&1

# Set track numbers automatically based on alphabetical sort
readarray -t files < <(fd -t f -e flac | sort)
for i in "${!files[@]}"; do
  metaflac --set-tag="TRACKNUMBER=$((i+1))" "${files[$i]}"
done

# Prompt for track titles
for f in "${files[@]}"; do
  track_title="$(gum input --prompt "Track title ${f}: " --placeholder "Enter title for track ${f}")"
  metaflac --set-tag="TITLE=${track_title}" "$f"
done

# Set year
fd -t f -e flac -X metaflac --set-tag="YEAR=${release_year}"

# Set artist
fd -t f -e flac -X metaflac --set-tag="ARTIST=${artist}"

# Set album name
fd -t f -e flac -X metaflac --set-tag="ALBUM=${album_name}"

gum log "All tags set!"
gum log "Album can be found in: '${album_dir}'"
