#!/usr/bin/env bash
# Synchronize select albums from remote storage to local storage,
# for offline use.
set -euo pipefail


# Declare list of artists whose albums we want to cache locally
artists=(
  "Sole"
  "Sole & DJ Pain 1"
  "Cloudkicker"
)

# Declare src and dest paths
music_src_library_dir="/mnt/Valhalla/Media/Heimchen"
music_dst_dir="${HOME:?}/music"
mkdir -p "$music_dst_dir"

# Hint: use SC2128 docs for consult on array expansion in bash:
# https://www.shellcheck.net/wiki/SC2128
#
# A bit of informative messaging
gum log "Synchronizing music for:"
gum log ""
for a in "${artists[@]}"; do
  printf '\t * %s\n' "$a"
done
gum log ""

# Copy the files via rsync.
# for a in "${artists[@]}"; do
#   gum spin --title "Synchronizing music... $a" -- \
#     rsync -aq "${music_src_library_dir}/${a}" "${music_dst_dir}/"
# done
# Change directory to make expansion easier
pushd "$music_src_library_dir" > /dev/null 2>&1
trap 'popd > /dev/null 2>&1' EXIT
gum spin --title "Synchronizing music..." --show-error --show-output -- \
  rsync -aq  "${artists[@]}" "${music_dst_dir}/"
gum log "All artists copied"

# Provide summary and exit.
music_dir_size="$(du -sh "$music_dst_dir" | perl -lanE 'say $F[0]' | perl -npE 's/\s*//g')"
gum log "Music dir size: $music_dir_size"
