#!/bin/bash
# Run a role against a target host via Ansible, without a playbook.
set -e
set -u

if [[ $# < 2 ]] ; then
    echo "Usage: $0 <role> <host>"
    exit 1
fi

role=$1
hosts=$2
shift 2

echo "Applying '${role}' to ${hosts}..."

tmpfile=$(mktemp --tmpdir="$PWD" --suffix="-temporary-ansible-playbook")
cat > $tmpfile <<PLAYBOOK
---
- hosts: $hosts
  roles:
  - $role
PLAYBOOK

trap "rm '${tmpfile}'" EXIT

ansible-playbook "${tmpfile}" "$@"
