#!/bin/bash
# Run a single task list against a target host via Ansible.
set -e
set -u

if [[ $# < 2 ]] ; then
    echo "Usage: $0 <task> <host>"
    exit 1
fi

task=$1
hosts=$2
shift 2

echo "Applying '${task}' to ${hosts}..."

tmpfile=$(mktemp --tmpdir="$PWD" --suffix="-temporary-ansible-task")
cat > $tmpfile <<PLAYBOOK
---
- hosts: $hosts
  tasks:
  - include: $task
PLAYBOOK

trap "rm '${tmpfile}'" EXIT

ansible-playbook "${tmpfile}" "$@"
