#!/bin/bash
# Read IP address from ansible inventory and pass to SSH.
# Does NOT include other SSH options such as user, port, key, etc.
set -e
set -u
set -o pipefail


target_host="$1"
shift 1

ip_address=$(ansible -m debug \
    -a msg="{{ hostvars['${target_host}']['ansible_ssh_host']}}" "${target_host}" \
    | head -n -2 \
    | tail -n 1 \
    | perl -F -lanE '/^\s+"msg": "([^"]+)"$/ and say $1')

if [[ -z "$ip_address" ]] ; then
    printf "Could not find IP address for host '%s'\n." "${target_host}"
    exit 1
fi

ssh "${ip_address}"
