#!/bin/sh -e
# via https://faq.i3wm.org/question/83/how-to-run-i3lock-after-computer-inactivity/


# Create temp file
screen_locked="$(mktemp --suffix '.png')"
# Take a screenshot
scrot "${screen_locked}"

# Pixellate it 10x
mogrify -scale 10% -scale 1000% "${screen_locked}"

# Lock screen displaying this image.
i3lock -i "${screen_locked}"

# Turn the screen off after a delay.
# sleep 60; pgrep i3lock && xset dpms force off
