#!/usr/bin/python
from BeautifulSoup import BeautifulSoup
import requests
import sys

IMDB_BASE_URL = "http://www.imdb.com"
IMDB_QUERY_ROUTE = IMDB_BASE_URL + "/find?q="
        
if len(sys.argv) < 2:
    sys.exit("Provide a word to look up.")

query = sys.argv.pop()

def findFirstResult(query):

    r = requests.get(IMDB_QUERY_ROUTE + query)
    soup = BeautifulSoup(r.content, convertEntities=BeautifulSoup.HTML_ENTITIES)
    hits = soup.findAll('a', heef=True, text=query.title());
    hits = soup.findAll('td',attrs={'class':'result_text'});

    # Assume top hit is the right one.
    th = hits[0]
    m = th.findChild()
    movie_title = m.contents
    movie_url = IMDB_BASE_URL + m.attrs[0][1]
    return movie_url

def parseMoviePage(movie_url):

    r = requests.get(movie_url)
    soup = BeautifulSoup(r.content, convertEntities=BeautifulSoup.HTML_ENTITIES)

    y = soup.find('span', attrs={'class': 'nobr'})
    year = y.findChildren()[0].getText()

    t = soup.find('span', attrs={'itemprop': 'name'})
    title = t.getText()

    d = soup.find('div', attrs={'itemprop': 'director'})
    director = d.findChildren()[1].getText()

    w = soup.find('div', attrs={'itemprop': 'creator'})
    writer = d.findChildren()[1].getText()

    a = soup.find('div', attrs={'itemprop': 'actors'})
    a.findAll('span', attrs={'itemprop': 'name'})[0].getText()
    actors = [ person.getText() for person in a.findAll('span', attrs={'itemprop': 'name'})]

    movie = {
            'title': title,
            'year': year,
            'director': director,
            'writer': writer,
            'actors': actors,
            'url': movie_url
            }

    return movie

def findMovie(query):
    m = findFirstResult(query)
    info = parseMoviePage(m)
    return info

def movieDescription(m):

    description = """\
%(title)s (%(year)s)
Directed by %(director)s
Written by %(writer)s
""" %  {'title': m['title'], 
    'year': m['year'],
    'director': m['director'],
    'writer': m['writer'],
    }

    description += "Starring:\n"
    for a in m['actors']:
        description += "\t- %s\n" % a

    print description

m = findMovie(query)
movieDescription(m)
