#!/bin/bash
# script to convert magnet URIs to torrents
# from: http://wiki.rtorrent.org/MagnetUri

remote_directory='do-general:torrents/' # set location magnet file should be copied to
cd /tmp || exit # save magnet file locally to tmp, because it will be converted
[[ "$1" =~ xt=urn:btih:([^&/]+) ]] || exit
hashh=${BASH_REMATCH[1]}
if [[ "$1" =~ dn=([^&/]+) ]];then
    filename=${BASH_REMATCH[1]}
else
    filename=$hashh
fi
torrent_name="meta-${filename}.torrent"
echo "d10:magnet-uri${#1}:${1}e" > "${torrent_name}" # create torrent file
scp "${torrent_name}" "${remote_directory}/${torrentname}" # move torrent file to remote watching directory;

