#!/bin/bash
# dual-monitor configs for various machines
# add configs by hostname

if [[ $(hostname) == 'kestrel' ]]; then 
   # desktop workstation, two widescreen monitors with left profile and right landscape
   LMON='DisplayPort-0'
   RMON='DVI-0'
   xrandr --output $LMON --left-of $RMON --rotate right
   xrandr --output $RMON --primary

elif [[ $(hostname) == 'Petrichor' ]]; then
   # laptop, usually just the one screen, sometimes a VGA connected externally 
   # if no external screen is plugged in, this won't do anything (which is good)
   EXTERNAL_MONITOR='VGA1'
   INTERNAL_MONITOR='LVDS1'
   xrandr --auto
   xrandr --output $EXTERNAL_MONITOR
   xrandr --output $INTERNAL_MONITOR --primary
   if [[ $# -ne 0 && "$1" == "no-rotate" ]] ; then
       xrandr --output $EXTERNAL_MONITOR --left-of $INTERNAL_MONITOR --rotate normal
   else
       xrandr --output $EXTERNAL_MONITOR --left-of $INTERNAL_MONITOR --rotate left
   fi

elif [[ $(hostname) == 'Way' ]]; then
   # another laptop (I really need to refactor this script)
   EXTERNAL_MONITOR='HDMI2'
   INTERNAL_MONITOR='eDP1'
   xrandr --auto
   xrandr --output $EXTERNAL_MONITOR
   xrandr --output $INTERNAL_MONITOR --primary
   if [[ $# -ne 0 && "$1" == "no-rotate" ]] ; then
       xrandr --output $EXTERNAL_MONITOR --left-of $INTERNAL_MONITOR --rotate normal
   else
       xrandr --output $EXTERNAL_MONITOR --left-of $INTERNAL_MONITOR --rotate left
   fi

elif [[ $# -ne 0 && "$3" == "projector" ]] ; then
   # laptop hooked up to a projector. identify and configure that
   # project.
   PROJECTOR='VGA1'
   INTERNAL_MONITOR='LVDS1'
   xrandr --auto
   xrandr --output $PROJECTOR --left-of $INTERNAL_MONITOR
   xrandr --output $INTERNAL_MONITOR --primary
fi

# redraw desktop (fixes both orientation and tiling issues)
nitrogen --restore > /dev/null 2>&1
