#!/bin/bash
# dual-monitor configs for various machines
# add configs by hostname
set -e
set -o pipefail

set -x
# set up some default vars shared across hosts
primary_monitor=$(xrandr | perl -nE '/^(\w+) connected primary / && say $1')
secondary_monitor=$(xrandr | perl -nE '/^(\w+) connected (?!primary)/ && say $1')

if [[ -z "${secondary_monitor}" ]] && [[ "$1" -ne "solo" ]] ; then
    echo "No secondary monitor found."
    exit 1
fi

secondary_side="left"

xrandr --auto
primary_monitor="eDP1"
xrandr --output "${primary_monitor}" --primary
if [[ $# -ne 0 && "$1" == "no-rotate" ]] ; then
   xrandr --output "${secondary_monitor}" "--${secondary_side}-of" "${primary_monitor}" --rotate normal
elif [[ $# -ne 0 && "$1" == "solo" ]] ; then
   set +e
   xrandr --output "${secondary_monitor}" --off
   xrandr --output "${primary_monitor}" --primary
   set -e
else
   xrandr --output "${secondary_monitor}" "--${secondary_side}-of" "${primary_monitor}" --rotate left
fi
# redraw desktop (fixes both orientation and tiling issues)
nitrogen --restore > /dev/null 2>&1
