#!/usr/bin/env python
import netifaces
import nmap


scanner = nmap.PortScanner()
scan_results = scanner.scan(hosts='10.0.0.*', arguments='-sP')

active_hosts = scan_results['nmap']['scanstats']['uphosts']
print("Found {0} active hosts on network.".format(active_hosts))

# No idea how portable this is
local_ip = netifaces.ifaddresses('wlan0')[2][0]['addr']

def get_host_info():
    for ip_address, metadata in scan_results['scan'].items():
        info = ip_address
        hostname = metadata['hostname']
        if hostname:
            info += " ({0})".format(hostname)
        if ip_address == local_ip:
            info += " (This is you.)"
        yield info

for i in sorted(get_host_info()):
    print(i)


