#!/usr/bin/perl 
#Script to generate output for status bar for tmux. 
#Output will be formatted differently for desktops and laptops, 
#such as displaying wifi connection or battery charging status.

#add these options to your ~/.tmux.conf
#to ensure this script displays well: 

#set -g default-terminal "screen-256color"
#set -g status-right '#(tmux_status)' 
#set-option -g status-right-length 80

#On a laptop, it should look like:
#SSID-CONNECTED user@hostname 77%/time_left tempC MM/DD HH/MM
#On a desktop, it should look like:  #not well implemented yet;
#inet[green/red] user@hostname tempC MM/DD HH/MM

use strict;
use warnings;
use diagnostics;
use feature qw/switch say/;
use Term::ANSIColor;

`laptop-detect`; #returns 0 if laptop, any other exit code is failure;
my $laptop_check = $?; #capture exit code of laptop-detect;

sub print_colored { #outputs given string encased in tmux-compatible color codes;
    my ($string, $color) = @_; #unpack variables from function caller;

    my %colors = ( #build hash for easy access to common tmux-compatible colors;
            black => '#[fg=black]', 
            red => '#[fg=red]',
            green => '#[fg=green]',
            brown => '#[fg=brown}',
            blue => '#[fg=blue]',
            magenta => '#[fg=magenta]',
            cyan => '#[fg=cyan]',
            white => '#[fg=white]',
            yellow => '#[fg=yellow]',
            orange => '#[fg=orange]',
            reset => '#[default]',
            );

    my $code = $colors{$color}; #retrieve necessary color code from hash;
    my $reset_code= "$colors{reset}"; #retrieve reset code from hash;
    my $new_string = "$code" . "$string"; #build new string, concatenating with color code;
    print "$new_string"; #print out string formatted with specified color;
    print "$reset_code"; #set terminal color back to normal;
}

#####LAPTOP#####
sub me { #return a 'me' identity in the form of user@hostname;
    my $username = `whoami`; #grab username from shell;
    my $hostname = `hostname`; #grab hostname from shell;
    chomp ($username, $hostname); #remove trailing newlines;
    my $me = $username . '@' . $hostname; #concatenate username and hostname with @ symbol;
    print "$me "; #print it;
}

sub battery_info {
    my $power_state; #initialize variable for construction;

    #example outputs of different states from acpi (v1.6), for reference:
    #my $charging_output =       "Battery 0: Charging, 62%, 00:49:05 until charged";
    #my $discharging_output =    "Battery 0: Discharging, 70%, 04:44:00 remaining";
    #my $full_output =           "Battery 0: Full, 100%";

    my $acpi_battery = `acpi -b`; #grab battery output of acpi command for processing;
    chomp $acpi_battery; #remove pesky trailing newline;

    given ($acpi_battery) { #take a look at the output from acpi command;
        when (/Discharging/) { #when AC adapter is unplugged;
            $power_state = "drng"; } #set power_state to more succinct mention that battery is draining;
        when (/Charging/) { #when AC adapter is plugged in;
            $power_state = "chrgng"; } #set power_state to more succinct mention that battery is charging;
        when (/Charged/) { #when battery is fully charged;
            $power_state = "full"; }  #set power-state to more succinct mention that battery if full;
        default { } #do nothing, for unforeseen corner cases;
    }

    $acpi_battery =~ m/(\d*)%/; #look for 0%, 00%, or 000% format percentage;
    my $percent_charged = $1; #name the matched group (00% format, above) for returning;
    $acpi_battery =~ m/(\d{2}:\d{2}:\d{2})/; #look for 00:00:00 format time;
    my $time_left = $2; #name matched group (00:00:00 format, above) for returning;

    given ($power_state) { #format display of charging icon;
        when (/chrgng/)         { print_colored ('⌁', 'green') }
        when (/drng/)           { print_colored ('⌁', 'red') }
        when (/full/)           { print_colored ('full', 'green') }
        default                 { } #do nothing, for unforeseen corner cases;
    };

    given ($percent_charged) { #format display of battery charge percentage;
        when ($_ > 90)                  { print_colored ("$percent_charged%", 'green') }
        when ($_ > 50 && $_ <= 90)      { print "$percent_charged%" }
        when ($_ > 20 && $_ <= 50)      { print_colored ("$percent_charged%", 'yellow') }
        when ($_ <= 20)                 { print_colored ("$percent_charged%", 'red') } 
        default                         { } #do nothing, for unforeseen corner cases; 
    };

    print '/'; #pretty separator for percent_charged and time_left;
    print "$time_left " #print hour many hours, minutes, and seconds of battery time remain;
        if defined($time_left); #only print if there's a value (undef if battery full);

}

sub temp { #return temperature from acpi shell call in format 00C;
    if ( $laptop_check eq 0 ) { #if probably on laptop;
        my $acpi_temp = `acpi -t`; #grab temperature output from acpi command (in Celsius);
        chomp $acpi_temp; #remove pesky trailining newline;
        $acpi_temp =~ s/^Thermal \d: \w+, //; #Strip out everything before temperature;
        $acpi_temp =~ s/(\d+)(\.)(.*$)/$1/; #Strip off everything but integer value of temp;
        #$acpi_temp = $acpi_temp . "C"; #concatenate temperature digits with units (here, C);
        given ($acpi_temp) {
            when ( $_ < 45 )                { print_colored($acpi_temp . 'C ', 'cyan') }
            when ( $_ >= 45 && $_ < 60 )    { print $acpi_temp . 'C ' }
            when ( $_ >= 60 )               { print_colored($acpi_temp . 'C ', 'red') }
            default                         { } #do nothing, for unforeseen corner cases;
        };
    }
}

sub date_and_time { #return date and time information, using Perl's localtime built-in function;
    my $date_and_time = `date +'%m/%d %H:%M'`; #grab time and date as mm/dd HH:MM;
    chomp $date_and_time; #remove pesky trailing newline;
    print $date_and_time; #print out data and time
}

sub network_status { #check whether connected to network and report it;
    `nm-online -t 2`; #run check (returns 0 for success, 1 for failure);
    if ( $? == 0 ) { #check whether connection check reported success;

        #get device name for active connection;
        my $device; #initialize variable in proper scope for printing;
        my @device_check = `nmcli dev`; #grab list of devices managed by NetworkManager;
        foreach my $device_candidate (@device_check) { #
            chomp $device_candidate; #remove pesky trailing newline;
            next unless $device_candidate =~ m/connected/; #skip unless line contains "connected";
            my @line = split('\s', $device_candidate);
            $device = shift @line; #grab first column of this line;
            last; #take first connected device;
        }
        
        print_colored ($device, 'green'); #if success, green means good;
        if ( $device =~ m/(wlan|ath)\d+/ ) { #if device appears to be a wireless connection;
            my $ssid = `iwgetid --raw`; #grab SSID of current network connection;
            chomp $ssid; #remove pesky trailing newline;
            print ":$ssid "; #print it;
        }
        else { #if not on a wifi connection, no SSID to display;
            print ' '; #add a single space for readability;
        }
    }

    else { #if capturing network status returned failure;
        print_colored ('no_net ', 'red'); #if failed, red means bad;
        print " "; #add space after output for nicer formatting;
    }
} 

sub print_status { #output status information to STDOUT;
    network_status; #report network connection status;
    me; #report 'user@hostname' string;
    battery_info #print statistics on battery charge status and time remaining;
        if $laptop_check eq 0; #only do this if running on a laptop;
    temp; #report CPU temperature in Celsius;
    date_and_time; #give date and time information;
    print ' '; #padding on the right-edge;
}

print_status; #create and output line according to above subroutine; 
