#!/bin/bash
set -e
set -o pipefail


[ $# -eq 0 ] && { echo "Usage: $0 <on|off|status>"; exit 1; }

vpn_enabled() {
   nmcli -t -f name,type,active con | grep -q -P '^\w+:vpn:yes'
}

# Set name of VPN connection in network manager.
# Will be grepped for, so substring matching OK.
vpn_connection_name="vpn"

# Ensure VPN connection is enabled.
case "$1" in
	on)
        # Check for existing VPN connection, since
        # trying to connect after connection exists will
        # throw error and disconnect the VPN.
        if ! vpn_enabled ; then
            nmcli con up id "${vpn_connection_name}"
        fi
        ;;
    off)
        # Only disable the VPN if it's currently enabled.
        if vpn_enabled ; then
            nmcli con down id "${vpn_connection_name}"
        fi
        ;;
    status)
        if vpn_enabled ; then
            echo "VPN status: enabled."
        else
            echo "VPN status: disabled"
        fi
        ;;
esac

