# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama
clients:
- type: openai-compatible
  name: ollama
  # api_base: http://localhost:11434/v1
  api_base: http://tartessos.ruindev.wg:6666/v1
  # api_base: https://llm.ruin.dev/v1
  # don't set API key in YAML config; aichat will read `OLLAMA_API_KEY` env var.
  # api_key: xxx # optional
  models:
    - name: qwen3.5:9b
      max_input_tokens: 256000
      enable_thinking: false
      patch:
        body:
          chat_template_kwargs:
            enable_thinking: false

    - name: qwen3.5:35b
      max_input_tokens: 256000
    - name: qwen3-coder-next:latest
      max_input_tokens: 256000
