import = [
    # "~/.config/alacritty/themes/themes/{theme}.toml"
    # "~/.config/alacritty/themes/themes/blood_moon.toml",
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/themes/gnome_terminal.toml",
    # "~/.config/alacritty/themes/themes/papercolor_dark.toml",
]
