import = [
    # "~/.config/alacritty/themes/themes/{theme}.toml"
    # "~/.config/alacritty/themes/themes/blood_moon.toml",
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/themes/gnome_terminal.toml",
    # "~/.config/alacritty/themes/themes/papercolor_dark.toml",
]

[font]
# Setting monospace font family by itself isn't enough; see also
# `~/.config/fontconfig/fonts.conf`, which forces use of an emoji-capable font.
normal.family = "monospace"
