# flakes forever
experimental-features = nix-command flakes

# reference harmonia nix cache on antigonus
substituters = https://cache.nixos.org https://cache.ruin.dev
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= antigonus.ruindev.wg-1:mZ/88onQ2NZqtnPDI7X7ZuxDzw8RRS0FKK5uTu2ERSg=
